table FabricWorkspaces

	column id
		dataType: string
		sourceColumn: id

	column name
		dataType: string
		sourceColumn: name

	column type
		dataType: string
		sourceColumn: type

	column state
		dataType: string
		sourceColumn: state

	column capacityId
		dataType: string
		sourceColumn: capacityId

	partition FabricWorkspaces = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\fabric_workspaces.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"id", type text},
				        {"name", type text},
				        {"type", type text},
				        {"state", type text},
				        {"capacityId", type text}
				    })
				in
				    Typed
